name: ocean_change
description: An iOS/Android mobile app for Fishermen and other ocean goers to report useful observations to the Oregon Department of Fish and Wildlife (ODFW).
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.2
  firebase_storage: ^11.2.4
  intl: ^0.18.1

  csv: ^5.0.2
  path_provider: ^2.0.15
  share_plus: ^7.0.2

  flutter_map: ^4.0.0
  latlong2: ^0.8.0
  flutter_map_marker_popup: ^4.1.0
  flutter_map_marker_cluster: ^1.1.1
  image_picker: ^1.0.1
  flutter_offline: ^3.0.0
  firebase_auth: ^4.7.2
  google_sign_in: ^6.1.4
  geolocator: ^9.0.2
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/

  # Map Assets  
   - assets/map/5/3/
   - assets/map/5/4/
   - assets/map/5/5/

   - assets/map/6/7/
   - assets/map/6/8/
   - assets/map/6/9/
   - assets/map/6/10/

   - assets/map/7/14/
   - assets/map/7/15/
   - assets/map/7/16/
   - assets/map/7/17/
   - assets/map/7/18/
   - assets/map/7/19/
   - assets/map/7/20/
   - assets/map/7/21/

   - assets/map/8/28/
   - assets/map/8/29/
   - assets/map/8/30/
   - assets/map/8/31/
   - assets/map/8/32/
   - assets/map/8/33/
   - assets/map/8/34/
   - assets/map/8/35/
   - assets/map/8/36/
   - assets/map/8/37/
   - assets/map/8/38/
   - assets/map/8/39/
   - assets/map/8/40/
   - assets/map/8/41/
   - assets/map/8/42/
   
   - assets/map/9/56/
   - assets/map/9/57/
   - assets/map/9/58/
   - assets/map/9/59/
   - assets/map/9/60/
   - assets/map/9/61/
   - assets/map/9/62/
   - assets/map/9/63/
   - assets/map/9/64/
   - assets/map/9/65/
   - assets/map/9/66/
   - assets/map/9/67/
   - assets/map/9/68/
   - assets/map/9/69/
   - assets/map/9/70/
   - assets/map/9/71/
   - assets/map/9/72/
   - assets/map/9/73/
   - assets/map/9/74/
   - assets/map/9/75/
   - assets/map/9/76/
   - assets/map/9/77/
   - assets/map/9/78/
   - assets/map/9/79/
   - assets/map/9/80/
   - assets/map/9/81/
   - assets/map/9/82/
   - assets/map/9/83/
   - assets/map/9/84/

   - assets/map/10/113/
   - assets/map/10/114/
   - assets/map/10/115/
   - assets/map/10/116/
   - assets/map/10/117/
   - assets/map/10/118/
   - assets/map/10/119/
   - assets/map/10/120/
   - assets/map/10/121/
   - assets/map/10/122/
   - assets/map/10/123/
   - assets/map/10/124/
   - assets/map/10/125/
   - assets/map/10/126/
   - assets/map/10/127/
   - assets/map/10/128/
   - assets/map/10/129/
   - assets/map/10/130/
   - assets/map/10/131/
   - assets/map/10/132/
   - assets/map/10/133/
   - assets/map/10/134/
   - assets/map/10/135/
   - assets/map/10/136/
   - assets/map/10/137/
   - assets/map/10/138/
   - assets/map/10/139/
   - assets/map/10/140/
   - assets/map/10/141/
   - assets/map/10/142/
   - assets/map/10/143/
   - assets/map/10/144/
   - assets/map/10/145/
   - assets/map/10/146/
   - assets/map/10/147/
   - assets/map/10/148/
   - assets/map/10/149/
   - assets/map/10/150/
   - assets/map/10/151/
   - assets/map/10/152/
   - assets/map/10/153/
   - assets/map/10/154/
   - assets/map/10/155/
   - assets/map/10/156/
   - assets/map/10/157/
   - assets/map/10/158/
   - assets/map/10/159/
   - assets/map/10/160/
   - assets/map/10/161/
   - assets/map/10/162/
   - assets/map/10/163/
   - assets/map/10/164/
   - assets/map/10/165/
   - assets/map/10/166/
   - assets/map/10/167/
   - assets/map/10/168/
   - assets/map/10/169/

   - assets/map/11/226/
   - assets/map/11/227/
   - assets/map/11/228/
   - assets/map/11/229/
   - assets/map/11/230/
   - assets/map/11/231/
   - assets/map/11/232/
   - assets/map/11/233/
   - assets/map/11/234/
   - assets/map/11/235/
   - assets/map/11/236/
   - assets/map/11/237/
   - assets/map/11/238/
   - assets/map/11/239/
   - assets/map/11/240/
   - assets/map/11/241/
   - assets/map/11/242/
   - assets/map/11/243/
   - assets/map/11/244/
   - assets/map/11/245/
   - assets/map/11/246/
   - assets/map/11/247/
   - assets/map/11/248/
   - assets/map/11/249/
   - assets/map/11/250/
   - assets/map/11/251/
   - assets/map/11/252/
   - assets/map/11/253/
   - assets/map/11/254/
   - assets/map/11/255/
   - assets/map/11/256/
   - assets/map/11/257/
   - assets/map/11/258/
   - assets/map/11/259/
   - assets/map/11/260/
   - assets/map/11/261/
   - assets/map/11/262/
   - assets/map/11/262/
   - assets/map/11/263/
   - assets/map/11/264/
   - assets/map/11/265/
   - assets/map/11/266/
   - assets/map/11/267/
   - assets/map/11/268/
   - assets/map/11/269/
   - assets/map/11/270/
   - assets/map/11/271/
   - assets/map/11/272/
   - assets/map/11/273/
   - assets/map/11/274/
   - assets/map/11/275/
   - assets/map/11/276/
   - assets/map/11/277/
   - assets/map/11/278/
   - assets/map/11/279/
   - assets/map/11/280/
   - assets/map/11/281/
   - assets/map/11/282/
   - assets/map/11/283/
   - assets/map/11/284/
   - assets/map/11/285/
   - assets/map/11/286/
   - assets/map/11/287/
   - assets/map/11/288/
   - assets/map/11/289/
   - assets/map/11/290/
   - assets/map/11/291/
   - assets/map/11/292/
   - assets/map/11/293/
   - assets/map/11/294/
   - assets/map/11/295/
   - assets/map/11/296/
   - assets/map/11/297/
   - assets/map/11/298/
   - assets/map/11/299/
   - assets/map/11/300/
   - assets/map/11/301/
   - assets/map/11/302/
   - assets/map/11/303/
   - assets/map/11/304/
   - assets/map/11/305/
   - assets/map/11/306/
   - assets/map/11/307/
   - assets/map/11/308/
   - assets/map/11/309/
   - assets/map/11/310/
   - assets/map/11/311/
   - assets/map/11/312/
   - assets/map/11/313/
   - assets/map/11/314/
   - assets/map/11/315/
   - assets/map/11/316/
   - assets/map/11/317/
   - assets/map/11/318/
   - assets/map/11/319/
   - assets/map/11/320/
   - assets/map/11/321/
   - assets/map/11/322/
   - assets/map/11/323/
   - assets/map/11/324/
   - assets/map/11/325/
   - assets/map/11/326/
   - assets/map/11/327/
   - assets/map/11/328/
   - assets/map/11/329/
   - assets/map/11/330/
   - assets/map/11/331/
   - assets/map/11/332/
   - assets/map/11/333/
   - assets/map/11/334/
   - assets/map/11/335/
   - assets/map/11/336/
   - assets/map/11/337/
   - assets/map/11/338/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
